#include "HtmlReport.h"
#include <fstream>
#include <iostream>
#include <sstream>
#include <iomanip>
#include <ctime>
#include <map>

string HtmlReport::styleBlock() {
    return R"(
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; background: #f0f2f5; color: #1a1a2e; padding: 40px 20px; }
        .container { max-width: 1000px; margin: 0 auto; }
        h1 { text-align: center; margin-bottom: 8px; font-size: 28px; color: #16213e; }
        .subtitle { text-align: center; color: #666; margin-bottom: 32px; font-size: 14px; }
        .card { background: #fff; border-radius: 12px; padding: 24px; margin-bottom: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        .card h2 { font-size: 18px; margin-bottom: 16px; color: #16213e; border-bottom: 2px solid #e8e8e8; padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #16213e; color: #fff; padding: 10px 14px; text-align: left; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
        td { padding: 10px 14px; border-bottom: 1px solid #eee; font-size: 14px; }
        tr:hover td { background: #f8f9fa; }
        .badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; }
        .badge-ok { background: #d4edda; color: #155724; }
        .badge-warn { background: #fff3cd; color: #856404; }
        .badge-danger { background: #f8d7da; color: #721c24; }
        .badge-service { background: #d1ecf1; color: #0c5460; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 24px; }
        .stat-box { background: #fff; border-radius: 12px; padding: 20px; text-align: center; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        .stat-box .number { font-size: 32px; font-weight: 700; color: #16213e; }
        .stat-box .label { font-size: 13px; color: #888; margin-top: 4px; }
        .footer { text-align: center; margin-top: 32px; color: #aaa; font-size: 12px; }
    </style>
    )";
}

string HtmlReport::htmlHeader(const string& title) {
    return "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>" + title + "</title>" + styleBlock() + "</head><body><div class='container'>";
}

string HtmlReport::htmlFooter() {
    time_t now = time(0);
    string date = ctime(&now);
    date.pop_back();
    return "<div class='footer'>Generated by Shop-Inv System | " + date + "</div></div></body></html>";
}

void HtmlReport::generateProductReport(const Store& store, const string& filename) {
    ofstream file(filename);
    if (!file.is_open()) { cout << "Error creating report." << endl; return; }

    file << htmlHeader("Product & Inventory Report");
    file << "<h1>Product & Inventory Report</h1>";
    file << "<p class='subtitle'>Overview of all products, stock levels and categories</p>";

    int totalPhysical = 0, totalService = 0, totalUnits = 0, lowStockCount = 0;
    double totalValue = 0;
    for (const auto* p : store.getProducts()) {
        const PhysicalProduct* pp = dynamic_cast<const PhysicalProduct*>(p);
        if (pp) {
            totalPhysical++;
            totalUnits += pp->getQuantity();
            totalValue += pp->getQuantity() * pp->getPrice();
            if (pp->isLowStock()) lowStockCount++;
        } else {
            totalService++;
        }
    }

    file << "<div class='stats-grid'>";
    file << "<div class='stat-box'><div class='number'>" << store.getCategories().size() << "</div><div class='label'>Categories</div></div>";
    file << "<div class='stat-box'><div class='number'>" << totalPhysical << "</div><div class='label'>Physical Products</div></div>";
    file << "<div class='stat-box'><div class='number'>" << totalService << "</div><div class='label'>Services</div></div>";
    file << "<div class='stat-box'><div class='number'>" << totalUnits << "</div><div class='label'>Total Units</div></div>";
    file << fixed << setprecision(2);
    file << "<div class='stat-box'><div class='number'>" << totalValue << "</div><div class='label'>Inventory Value</div></div>";
    file << "<div class='stat-box'><div class='number'>" << lowStockCount << "</div><div class='label'>Low Stock Alerts</div></div>";
    file << "</div>";

    file << "<div class='card'><h2>Categories</h2><table>";
    file << "<tr><th>ID</th><th>Name</th><th>Products</th></tr>";
    for (const auto* c : store.getCategories()) {
        int count = 0;
        for (const auto* p : store.getProducts())
            if (p->getCategoryId() == c->getId()) count++;
        file << "<tr><td>" << c->getId() << "</td><td>" << c->getName()
             << "</td><td>" << count << "</td></tr>";
    }
    file << "</table></div>";

    file << "<div class='card'><h2>Products</h2><table>";
    file << "<tr><th>ID</th><th>Name</th><th>Type</th><th>Price</th><th>Barcode</th><th>Stock</th><th>Status</th></tr>";
    for (const auto* p : store.getProducts()) {
        file << "<tr>";
        file << "<td>" << p->getId() << "</td>";
        file << "<td>" << p->getName() << "</td>";

        const PhysicalProduct* pp = dynamic_cast<const PhysicalProduct*>(p);
        const ServiceProduct* sp = dynamic_cast<const ServiceProduct*>(p);

        if (pp) {
            file << "<td>Physical</td>";
            file << "<td>" << fixed << setprecision(2) << pp->getPrice() << "</td>";
            file << "<td>" << pp->getBarcode() << "</td>";
            file << "<td>" << pp->getQuantity() << "</td>";
            if (pp->getQuantity() == 0)
                file << "<td><span class='badge badge-danger'>Out of stock</span></td>";
            else if (pp->isLowStock())
                file << "<td><span class='badge badge-warn'>Low stock</span></td>";
            else
                file << "<td><span class='badge badge-ok'>In stock</span></td>";
        } else if (sp) {
            file << "<td><span class='badge badge-service'>Service</span></td>";
            file << "<td>" << fixed << setprecision(2) << sp->getPrice() << "</td>";
            file << "<td>" << sp->getBarcode() << "</td>";
            file << "<td>—</td>";
            file << "<td><span class='badge badge-service'>" << sp->getDuration() << " min</span></td>";
        }
        file << "</tr>";
    }
    file << "</table></div>";

    file << htmlFooter();
    file.close();
    cout << "Product report saved to " << filename << endl;
}

void HtmlReport::generateFullReport(const Store& store, const string& filename) {
    generateProductReport(store, filename);
}
